### ISSUE TITLE
图片组件无法正常显示

### ISSUE THREAD

**Issue by Misaka-L** [laiyuzenb/kook_message_preview#1]
## 问题描述

如图，图片组件没有按正常大小显示图片。而是以一个极小的大小显示图片。

![image](https://github.com/laiyuzenb/kook_message_preview/assets/42287372/a00fa1b6-8371-4cdb-9984-22f6b583e3d5)

通过 DevTools 发现图片组件在 style 属性设置了个极小的高度和宽度

![image](https://github.com/laiyuzenb/kook_message_preview/assets/42287372/3961cbb1-652b-4a56-b097-b30d5cad37d8)

另外翻阅源代码发现，图片组件是引用了 `@kaiheila/kui-lib`，但本人未找到相关仓库。

## 临时解决方案

在应用的 css 文件添加以下片段：

```css
.kui-image {
  height: fit-content !important;
  width: 100% !important;
}
```

![image](https://github.com/laiyuzenb/kook_message_preview/assets/42287372/161ba02e-76c4-4b37-8117-51211c078223)
