### ISSUE TITLE
文件组件无法正常显示

### ISSUE THREAD

**Issue by Misaka-L** [laiyuzenb/kook_message_preview#2]
## 问题描述

如图所示，文件组件文件标题不正常居中。

![image](https://github.com/laiyuzenb/kook_message_preview/assets/42287372/3ca7d3ad-696a-4c77-ba90-fe0c1c40270a)

## 临时解决方案

在应用 css 文件添加以下片段

```css
.kui-file .file-content .file-info {
  align-items: start;
}
```
