### ISSUE TITLE
支持 invisible 卡片

### ISSUE THREAD

**Issue by Misaka-L** [laiyuzenb/kook_message_preview#5]
KOOK 已支持 invisible 类型的卡片，但预览组件暂未跟进

**Comment by FeClickEngineer** [comment]
暂不考虑支持，因为invisible主题还有业务逻辑，后续还会调整样式，等帖子上了后 不频繁改动样式后 再跟进

**Comment by Misaka-L** [comment]
如果需要支持 invisible 卡片，这有一个临时的 wrokaround...

```css
.kui-card.type-invisible {
  border: none;
  background: none;
  padding: 0;
}
```

**Comment by FeClickEngineer** [comment]
@Misaka-L 
``` css
.type-invisible {
      background-color: transparent;
      border-left: none;
      padding: 0;
      width: 100%;
      max-width: 100%;
      margin-top: 0px;

      .no-extra {
        padding-top: 0;
        padding-bottom: 0;
      }

      .kui-section .section-content {
        font-size: 16px;
      }

      &.kui-card {
        display: flex;
        flex-direction: column;
        gap: 4px;
        padding-bottom: 0;
      }

      .kui-container {
        padding: 0;
      }

      .kui-video {
        padding: 0;
        max-width: 436px;
      }

      .kui-file {
        padding: 0;
        background-color: var(--color-top-bg);
        padding: 12px;
        max-width: 436px;
      }

      .kui-music {
        padding: 0;
        background-color: var(--color-top-bg);
        padding: 12px;
        max-width: 436px;

        .kui_iconfont {
          margin-left: 0;
        }

        .music-content-icons {
          flex-direction: row-reverse;
          gap: 4px;
        }
      }
    }
```
